<a href="https://colab.research.google.com/github/tnaka78/recsys-python/blob/main/recsys_python_chap01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# recsys-python 第1章 評価履歴
https://recsyslab.github.io/recsys-python/ja/chap01.html

In [ ]:
import numpy as np

## 評価履歴

In [ ]:
Du = np.array(
  [[ 5.,  3.,  1.],
   [ 6.,  2.,  1.],
   [ 4.,  1.,  1.],
   [ 8.,  5., -1.],
   [ 2.,  4., -1.],
   [ 3.,  6., -1.],
   [ 7.,  6., -1.],
   [ 4.,  2., np.nan],
   [ 5.,  1., np.nan],
   [ 8.,  6., np.nan],
   [ 3.,  4., np.nan],
   [ 4.,  7., np.nan],
   [ 4.,  4., np.nan]]
)
print('Du = \n{}'.format(Du))

Du = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]
 [ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


In [ ]:
print('Duの形状 = {}'.format(Du.shape))

Duの形状 = (13, 3)


In [ ]:
print('Duの行数 = {}'.format(Du.shape[0]))

Duの行数 = 13


In [ ]:
print('Duの列数 = {}'.format(Du.shape[1]))

Duの列数 = 3


In [ ]:
print('Duの全要素数 = {}'.format(Du.size))

Duの全要素数 = 39


## アイテム

In [ ]:
I = np.arange(Du.shape[0])
print('I = {}'.format(I))

I = [ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
x = Du[:, :2]
print('x = \n{}'.format(x))

x = 
[[5. 3.]
 [6. 2.]
 [4. 1.]
 [8. 5.]
 [2. 4.]
 [3. 6.]
 [7. 6.]
 [4. 2.]
 [5. 1.]
 [8. 6.]
 [3. 4.]
 [4. 7.]
 [4. 4.]]


In [ ]:
i = 0
print('x{} = {}'.format(i, x[i]))

x0 = [5. 3.]


In [ ]:
ru = Du[:, 2]
print('ru = {}'.format(ru))

ru = [ 1.  1.  1. -1. -1. -1. -1. nan nan nan nan nan nan]


In [ ]:
print('ruの形状 = {}'.format(ru.shape))

ruの形状 = (13,)


In [ ]:
print('ruの全要素数 = {}'.format(ru.size))

ruの全要素数 = 13


In [ ]:
i = 2
j = 5
print('ru{}からru{}までの評価値 = {}'.format(i, j-1, ru[i:j]))

ru2からru4までの評価値 = [ 1. -1. -1.]


In [ ]:
print('ruの逆順 = {}'.format(ru[::-1]))

ruの逆順 = [nan nan nan nan nan nan -1. -1. -1. -1.  1.  1.  1.]


In [ ]:
i = 0
print('ru{} = {}'.format(i, ru[i]))

ru0 = 1.0


## アイテム集合

In [ ]:
print('ユーザuが未評価 = {}'.format(np.isnan(ru)))

ユーザuが未評価 = [False False False False False False False  True  True  True  True  True
  True]


In [ ]:
print('ユーザuが評価済み = {}'.format(~np.isnan(ru)))

ユーザuが評価済み = [ True  True  True  True  True  True  True False False False False False
 False]


In [ ]:
Iu = I[~np.isnan(ru)]
print('Iu = {}'.format(Iu))

Iu = [0 1 2 3 4 5 6]


In [ ]:
Iup = I[ru == 1.0]
print('Iu+ = {}'.format(Iup))

Iu+ = [0 1 2]


In [ ]:
Iun = I[ru == -1.0]
print('Iu- = {}'.format(Iun))

Iu- = [3 4 5 6]


In [ ]:
Iu_not = I[np.isnan(ru)]
print('Iu_not = {}'.format(Iu_not))

Iu_not = [ 7  8  9 10 11 12]


## 訓練データと予測対象データ

In [ ]:
DuL = Du[Iu]
print('DuL = \n{}'.format(DuL))

DuL = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]]


In [ ]:
print('|DuL| = {}'.format(DuL.shape[0]))

|DuL| = 7


In [ ]:
print('|DuL+| = {}'.format(DuL[DuL[:, 2] == 1.0].shape[0]))

|DuL+| = 3


In [ ]:
print('|DuL-| = {}'.format(DuL[DuL[:, 2] == -1.0].shape[0]))

|DuL-| = 4


In [ ]:
DuU = Du[Iu_not]
print('DuU = \n{}'.format(DuU))

DuU = 
[[ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


In [ ]:
print('|DuU| = {}'.format(DuU.shape[0]))

|DuU| = 6
